### ISSUE TITLE
Most if not all Grove comment plague leftovers.

### ISSUE THREAD

**Issue by Domiiniik** [Sergeanur/UndefinifiedGrove#2]
Main.sc
*******************************************
Comment:War Drum plague? Check if the script does what this says in OG if not, it's a plague.

// WD_SCRIPT_BYPASS // now activates when you mission jump
*****************************************
Comment:3master plague

PRINT_HELP ( HELP42 ) // "This is the ~h~radar~w~. Use it to navigate the city. Follow the ~h~GPS route~w~ on the ~h~radar~w~ to get back to the hood."
*****************************************
Comment:3master plague

PRINT_HELP GF_RAD  // Swipe the bottom left corner of the screen to change radio stations. CONDITION_FLAG_RADIO_STATION
******************************************

**Comment by Domiiniik** [comment]
Main/misc/objects
slot_machine.sc
*************************************************
Comment:Mobile ver related plague.

  // Alphamode must manually be set to 2 in txd.txt for these textures.

**Comment by Domiiniik** [comment]
This is the last plague list issue comment, all of the .sc files have been checked, and most if not all plague comments leftovers are found.
*************************************************
Main/oddjobs/location
bikesch.sc
*************************************************
Comment:Mobile plague

// Do a Wheelie along the coned section. Accelerate to top speed, then double tap and hold the accelerator.
************************************************
Main/story_missions/LA1
la1fin1.sc
Comment: This is a WarDrum Plague and it should be 2 lines gap instead without this plague comment.

		//Why are these being cleared before the player can read them?"
**************************************
ryder1.sc
Comment:This is WD controls plague, as it's different in OG.

  // Walk over to the truck to drop the item.
*********************************************
Main/story_missions/LA1
sweet2.sc
Comment:Mobile ver plague

// To manually aim, touch the middle of the screen and move to the left and right whilst shooting.
********************************************
Main/story_missions/LA1
sweet2.sc
Comment:Second, same as the previous comment plague

// To manually aim, touch the middle of the screen and move to the left and right whilst shooting.
********************************************
Main/story_missions_LA2
mansion2.sc
Comment:Remastered plague (og help text is different)

  // Use the steering controls to tilt the plane forward and back.
********************************************
Main/story_missions_LA2
mansion2.sc
Comment:Remastered plague, second copy one.

  // Use the steering controls to tilt the plane forward and back.
*******************************************

**Comment by Sergeanur** [comment]
Cured
